services:
  streamlit:
    build: .   # points to your Dockerfile in current directory
    container_name: guestpost_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/home/appuser/.streamlit
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 5s
      retries: 5

