name: Deploy to EC2 (docker-compose plugin)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 & deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # --- Prepare working dir ---
            sudo mkdir -p /srv/app
            sudo chown $USER:$USER /srv/app
            cd /srv/app

            # --- Ensure Docker engine & compose plugin (idempotent) ---
            if ! command -v docker >/dev/null 2>&1; then
              # Install Docker engine via Docker's apt repo
              sudo apt-get update
              sudo apt-get install -y ca-certificates curl gnupg
              sudo install -m 0755 -d /etc/apt/keyrings
              if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              fi
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" \
                | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER || true
            else
              # Ensure compose plugin exists
              if ! docker compose version >/dev/null 2>&1; then
                sudo apt-get update
                sudo apt-get install -y docker-compose-plugin
              fi
            fi

            # Remove any stray old binary compose if present
            sudo rm -f /usr/local/bin/docker-compose || true

            # --- Sync repo ---
            if [ ! -d .git ]; then
              git clone https://github.com/SDRA123/email-scraper-verifier.git .
            else
              git fetch --all
              git reset --hard origin/main
            fi

            # --- Build & (re)start services ---
            docker compose pull || true
            docker compose up -d --build --remove-orphans

            # --- Housekeeping ---
            docker image prune -f || true
